### ISSUE TITLE
In which folder should this model be placed?

### ISSUE THREAD

**Issue by Elminsst** [MoonHugo/ComfyUI-BiRefNet-Hugo#7]
![image](https://github.com/user-attachments/assets/f4cbea61-2e3c-431b-9142-a17bf5a1795c)
It couldn't be downloaded automatically, so I downloaded it manually, but I don't know where to put it.

**Comment by MoonHugo** [comment]
> ![image](https://private-user-images.githubusercontent.com/130235860/365128517-f4cbea61-2e3c-431b-9142-a17bf5a1795c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MjI0ODIsIm5iZiI6MTcyNTYyMjE4MiwicGF0aCI6Ii8xMzAyMzU4NjAvMzY1MTI4NTE3LWY0Y2JlYTYxLTJlM2MtNDMxYi05MTQyLWExN2JmNWExNzk1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxMTI5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODU3OTk2N2NmMzcxNmZlNDY0MjcwZmZhNGMwODNmY2YyMDE1NTU4YWU2OGNiOGI0ZjYzZDNjMGIxMTY2MDFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FyjxK1nWBzyO8Lj1iTTF6FR32Cs8a_EU1OapTaqGD24) It couldn't be downloaded automatically, so I downloaded it manually, but I don't know where to put it.无法自动下载，所以我手动下载了，但不知道放在哪里。

The path on my local machine is C:\Users\25678.cache\huggingface\hub\models--ZhengPeng7--BiRefNet. You can refer to it or search for the directory “models--ZhengPeng7--BiRefNet” on your local system.

**Comment by wuqq** [comment]
我也是不能导入这个节点，提示错误如下
We couldn't connect to 'https://hf-mirror.com python xxx.py' to load this file, couldn't find it in the cached files and it looks like ZhengPeng7/BiRefNet is not the path to a directory containing a file named config.json.
这与你的错误是否一样的？
有解决办法了吗？

**Comment by peizhiluo007** [comment]
修改一下：直接传路径就可以了。
#birefnet = AutoModelForImageSegmentation.from_pretrained(
#    "ZhengPeng7/BiRefNet", trust_remote_code=True
#)
birefnet = AutoModelForImageSegmentation.from_pretrained(
   "模型本地存放路径(放哪里随你喜欢)", trust_remote_code=True
)
